# Generated by Django 4.1 on 2022-08-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV_Letter_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('Job_type', models.CharField(max_length=255)),
                ('Field_Applied', models.CharField(max_length=255)),
            ],
        ),
    ]
